spring:
  application:
    name: md-doc
md-doc:
  base-package: cn.isaxon.mddoc.example
  server-url: http://localhost:8080
  tag-index-number: chinese
  api-index-number: arabic
  title: Markdown API